// This file is auto-generated by scripts/generate-lesson-map.js. Do not edit manually.
const allLessons = {
  'duolingguo/lesson1.js': require('./duolingguo/lesson1.js'),
  'duolingguo/lesson2.js': require('./duolingguo/lesson2.js'),
  'duolingguo/lesson3.js': require('./duolingguo/lesson3.js'),
  'everyones_japanese/lesson31.js': require('./everyones_japanese/lesson31.js'),
  'everyones_japanese/lesson32.js': require('./everyones_japanese/lesson32.js'),
  'everyones_japanese/lesson33.js': require('./everyones_japanese/lesson33.js'),
  'everyones_japanese/lesson34.js': require('./everyones_japanese/lesson34.js'),
  'everyones_japanese/lesson35.js': require('./everyones_japanese/lesson35.js'),
  'everyones_japanese/lesson36.js': require('./everyones_japanese/lesson36.js'),
  'everyones_japanese/lesson37.js': require('./everyones_japanese/lesson37.js'),
  'everyones_japanese/lesson38.js': require('./everyones_japanese/lesson38.js'),
  'everyones_japanese/lesson44.js': require('./everyones_japanese/lesson44.js'),
  'everyones_japanese/lesson45.js': require('./everyones_japanese/lesson45.js'),
  'liangs_class/lesson17.js': require('./liangs_class/lesson17.js'),
  'liangs_class/lesson18.js': require('./liangs_class/lesson18.js'),
  'liangs_class/lesson19.js': require('./liangs_class/lesson19.js'),
  'liangs_class/lesson20.js': require('./liangs_class/lesson20.js'),
  'liangs_class/lesson21.js': require('./liangs_class/lesson21.js'),
  'liangs_class/lesson22.js': require('./liangs_class/lesson22.js'),
  'liangs_class/lesson23.js': require('./liangs_class/lesson23.js'),
};

module.exports = allLessons;
